# Generated by Django 5.0.7 on 2024-08-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_meshes',
            field=models.ManyToManyField(related_name='alerted_users', to='monitoring.mesh'),
        ),
    ]
