# Generated by Django 5.0.7 on 2024-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_phone_number'),
        ('monitoring', '0005_remove_meshsettings_check_download_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alert_meshes',
            field=models.ManyToManyField(blank=True, related_name='alerted_users', to='monitoring.mesh'),
        ),
    ]
