# Generated by Django 5.0 on 2024-07-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0002_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_address', models.CharField(max_length=50)),
                ('day_added', models.DateField(auto_now_add=True)),
                ('wallet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walletAssociated', to='wallet.wallet')),
            ],
        ),
    ]
