# Generated by Django 5.0.6 on 2024-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_dataratemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='granularity',
            field=models.IntegerField(blank=True, choices=[(3600, 'Hourly'), (86400, 'Daily'), (2678400, 'Monthly')], null=True),
        ),
    ]
