version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: inethi-manage-mysql
    environment:
      MYSQL_DATABASE: "manage"
      MYSQL_USER: "inethi"
      MYSQL_PASSWORD: "iNethi2023#"
      MYSQL_ROOT_PASSWORD: "iNethi2023#"
    volumes:
      - manage_db:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
    container_name: inethi-manage
    depends_on:
      - db
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      MYSQL_DATABASE: "manage"
      MYSQL_USER: "inethi"
      MYSQL_PASSWORD: "iNethi2023#"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  manage_db:
