# Generated by Django 5.0 on 2024-07-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
