# Generated by Django 5.0 on 2024-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_delete_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='qr_code',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
