# Generated by Django 5.0.6 on 2024-07-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRateMetric',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metrics.metric')),
                ('tx_rate', models.IntegerField(blank=True, null=True)),
                ('rx_rate', models.IntegerField(blank=True, null=True)),
            ],
            bases=('metrics.metric',),
        ),
    ]
