# Generated by Django 5.0.6 on 2024-07-26 19:25

import django.db.models.deletion
import macaddress.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('utility', 'utility'), ('entertainment', 'entertainment'), ('games', 'games'), ('education', 'education')], max_length=20)),
                ('api_location', models.CharField(choices=[('cloud', 'cloud'), ('local', 'local')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WlanConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('passphrase', models.CharField(blank=True, max_length=100, null=True)),
                ('security', models.CharField(choices=[('open', 'Open'), ('wpapsk', 'WPA-PSK')], max_length=6)),
                ('is_guest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('mac', macaddress.fields.MACAddressField(integer=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('is_ap', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hardware', models.CharField(choices=[('ubnt_ac_mesh', 'Ubiquiti AC Mesh'), ('tl_eap225_3_o', 'TPLink EAP')], default='tl_eap225_3_o', max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mesh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.mesh')),
                ('neighbours', models.ManyToManyField(blank=True, to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', macaddress.fields.MACAddressField(integer=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bytes_recv', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('uplink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(3, 'Critical'), (2, 'Warning'), (1, 'Decent'), (0, 'OK')])),
                ('text', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.node')),
            ],
        ),
        migrations.AddField(
            model_name='mesh',
            name='wlanconfs',
            field=models.ManyToManyField(blank=True, to='monitoring.wlanconf'),
        ),
    ]
