# Generated by Django 5.0.6 on 2024-08-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshsettings',
            name='alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
