# Generated by Django 5.0.6 on 2024-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='online',
        ),
        migrations.AddField(
            model_name='mesh',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mesh',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mesh',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='reboot_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('offline', 'Offline'), ('online', 'Online'), ('rebooting', 'Rebooting')], default='unknown', max_length=16),
        ),
    ]
