# Generated by Django 5.0.6 on 2024-08-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientSession',
        ),
    ]
