# Generated by Django 5.0.7 on 2024-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
