# Generated by Django 5.0.6 on 2024-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_node_online_mesh_lat_mesh_location_mesh_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='reachable',
            field=models.BooleanField(default=False),
        ),
    ]
