# Generated by Django 5.0.7 on 2024-08-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_alert_resolved_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='mesh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.mesh'),
        ),
    ]
