# Generated by Django 5.0.6 on 2024-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_node_last_ping_node_reachable'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('critical', 'Critical'), ('warning', 'Warning'), ('decent', 'Decent'), ('ok', 'Ok')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.SmallIntegerField(choices=[(2, 'Critical'), (1, 'Error'), (0, 'Warning')]),
        ),
    ]
