# Generated by Django 5.0.7 on 2024-08-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alert_mesh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshsettings',
            name='check_download_speed',
        ),
        migrations.RemoveField(
            model_name='meshsettings',
            name='check_ping',
        ),
        migrations.RemoveField(
            model_name='meshsettings',
            name='check_upload_speed',
        ),
    ]
