# Generated by Django 5.0.6 on 2024-07-18 17:09

import django.db.models.deletion
import macaddress.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('utility', 'Utility'), ('entertainment', 'Entertainment'), ('games', 'Games'), ('education', 'Education')], max_length=20)),
                ('api_location', models.CharField(choices=[('cloud', 'Cloud'), ('local', 'Local')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownNode',
            fields=[
                ('mac', macaddress.fields.MACAddressField(integer=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('mac', macaddress.fields.MACAddressField(integer=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hardware', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.mesh')),
                ('neighbours', models.ManyToManyField(blank=True, to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', macaddress.fields.MACAddressField(integer=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bytes_recv', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('uplink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='monitoring.node')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(3, 'Critical'), (2, 'Warning'), (1, 'Decent'), (0, 'OK')])),
                ('text', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.node')),
            ],
        ),
    ]
