# Generated by Django 5.0.6 on 2024-07-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
