# Generated by Django 5.0.6 on 2024-07-11 22:26

import django.db.models.deletion
import macaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_node_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', macaddress.fields.MACAddressField(integer=True)),
                ('username', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bytes_recv', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('uplink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='monitoring.node')),
            ],
        ),
    ]
